# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Supercoop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Supercoop
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage'
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'GoogleSignIn'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'
  pod 'RNSound', :path => '../node_modules/react-native-sound'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'
  pod 'react-native-cookies', :path => '../node_modules/react-native-cookies/ios'


  post_install do |installer|
      installer.pods_project.targets.each do |target|
          
          targets_to_ignore = %w(React yoga)
          
          if targets_to_ignore.include? target.name
              target.remove_from_project
          end
          
      end
  end
  
end
