# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Supercoopain' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Supercoopain
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'GoogleSignIn'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'SupercoopainTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
