# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version '2.53.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

platform :ios do
  # iOS Lanes
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'fr.supercoop.app-ios', type: 'development', readonly: true)
    match(app_identifier: 'fr.supercoop.app-ios', type: 'appstore', readonly: true)
  end

  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: "./ios/Supercoop.xcodeproj")
    build_app(workspace: "./ios/Supercoop.xcworkspace", scheme: "Supercoop")
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/name.xcodeproj')
    push_to_git_remote
  end

  desc "Upload Debug Symbols to Sentry"
  lane :upload_symbols do
    download_dsyms
    sentry_upload_dsym(
      url: 'https://sentry.akerbis.com',
      auth_token: 'd9f54e5a8d7041de95ca8b479f9c2c5190a3c6ee22e04b56a65440f309612d2c',
      org_slug: 'supercoop',
      project_slug: 'supercoop-mobile',
    )
  end
end

platform :android do
  # Android Lanes
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end
end
