# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version '2.53.1'

before_all do
  ensure_git_status_clean
  git_pull
end

platform :ios do
  # iOS Lanes
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'fr.supercoop.app-ios', type: 'development', readonly: true)
    match(app_identifier: 'fr.supercoop.app-ios', type: 'appstore', readonly: true)
  end

  desc 'Build the iOS application.'
  private_lane :build do
    build_app(workspace: "./ios/Supercoop.xcworkspace", scheme: "Supercoop")
  end

  desc 'Ship to Testflight.'
  lane :beta do
    ensure_git_branch(
      branch: '^release/.*$'
    )
    increment_build_number(xcodeproj: "./ios/Supercoop.xcodeproj")
    commit_version_bump(xcodeproj: './ios/Supercoop.xcodeproj')
    build
    upload_to_testflight
    push_to_git_remote
  end
end

platform :android do
  # Android Lanes
  desc 'Build the Android application.'
  private_lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'bundle', build_type: 'Release', project_dir: 'android/')
  end

  desc 'Ship to Playstore Beta.'
  lane :beta do
    ensure_git_branch(
      branch: '^release/.*$'
    )
    build
    supply(track: 'beta', track_promote_to: 'beta')
    git_commit(path: ['./android/gradle.properties'], message: 'Bump versionCode')
    push_to_git_remote
  end
end
