name: Typescript Compilation Errors

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install JS dependencies
        run: yarn install
      - name: Check Typescript Errors
        run: yarn tsc --noEmit
